insert into roles(name,description) values ('Administrator','Volledig beheer'),('Medewerker','Marketingwerk uitvoeren'),('Viewer','Alleen lezen') on conflict do nothing;
insert into permissions(key,description) select x,x from unnest(array['marketing_items.view','marketing_items.create','marketing_items.edit','marketing_items.delete','tasks.view','tasks.create','tasks.edit','tasks.assign','tasks.delete','tasks.approve','comments.create','templates.manage','concepts.manage','channels.manage','users.view','users.manage','roles.manage','reports.view','archive.view','files.upload','files.delete']) x on conflict do nothing;
insert into role_permissions select r.id,p.id from roles r cross join permissions p where r.name='Administrator' on conflict do nothing;
insert into role_permissions select r.id,p.id from roles r join permissions p on p.key in ('marketing_items.view','marketing_items.create','tasks.view','tasks.create','tasks.edit','tasks.assign','tasks.approve','comments.create','reports.view','archive.view','files.upload') where r.name='Medewerker' on conflict do nothing;
insert into role_permissions select r.id,p.id from roles r join permissions p on p.key in ('marketing_items.view','tasks.view','reports.view','archive.view','users.view') where r.name='Viewer' on conflict do nothing;
insert into channels(name) select unnest(array['Website','Instagram','Facebook','LinkedIn','Pinterest','B2B nieuwsbrief','B2C nieuwsbrief','Google Ads','Meta Ads','POS/showroommateriaal','Print','Folder','Ledenportaal','Externe website','DTP','Leadgeneratie','Overig']) on conflict do nothing;
insert into communication_profiles(name,type,country,description) values ('Keukenspecialisten.nl','Concept','Nederland','Consumentenconcept voor keukenspecialisten'),('Enviroo Keukens','Private Label','Nederland','Duurzaam keukenlabel'),('Mijn BAD in Stijl','Private Label','Nederland','Badkamerconcept'),('DER KREIS Nederland','Land/organisatie','Nederland','Nederlandse organisatie'),('DER KREIS België','Land/organisatie','België','Belgische organisatie'),('DER KREIS United Kingdom','Land/organisatie','Verenigd Koninkrijk','Britse organisatie') on conflict do nothing;
insert into marketing_item_types(name) select unnest(array['Campagne','Actie','Leveranciersnieuws','Nieuwe deelnemer','Offboarding deelnemer','Blog','Influencersamenwerking','Nieuwe showroom','Evenement','Nieuwsbrief','Socialplanning','Interne klus','Showroomondersteuning','Overig']) on conflict do nothing;
insert into tags(name) select unnest(array['AEG','Actie','Leverancier','SEO','Event','Leadgeneratie']) on conflict do nothing;
insert into settings(key,value) values ('workload_hours','{"Klein":0.5,"Middel":2,"Groot":4}'),('max_file_size_mb','20'),('theme','{"primary":"#235b44"}') on conflict do nothing;
insert into task_library(name,category,workload,channel_id) select 'Landingspagina aanmaken','Website','Middel',id from channels where name='Website';
insert into task_library(name,category,workload,channel_id) select 'Social visual ontwerpen','DTP','Middel',id from channels where name='DTP';
insert into task_library(name,category,workload,channel_id) select 'Nieuwsbriefitem maken','Nieuwsbrief','Klein',id from channels where name='B2B nieuwsbrief';
insert into workflow_templates(name,type_id,profile_id) select 'Nieuwe deelnemer - Keukenspecialisten.nl',t.id,p.id from marketing_item_types t,communication_profiles p where t.name='Nieuwe deelnemer' and p.name='Keukenspecialisten.nl';
insert into workflow_templates(name,type_id) select 'Offboarding deelnemer',id from marketing_item_types where name='Offboarding deelnemer';
insert into workflow_template_tasks(template_id,title,category,workload,sort_order) select wt.id,x.title,x.category,'Middel',x.ord from workflow_templates wt cross join (values('Micro/showroompagina aanmaken','Website',1),('Showroom-ID controleren','Website',2),('Store locator toevoegen','Website',3),('Afspraakformulier activeren','Formulieren',4),('Reviewformulier activeren','Formulieren',5),('Showroombeelden opvragen','Communicatie',6),('Deelnemer aanmaken in DBMC','Leadgeneratie',7),('Leadstroom controleren','Leadgeneratie',8),('Ondernemer melden dat pagina online staat','Communicatie',9)) x(title,category,ord) where wt.name like 'Nieuwe deelnemer%';
insert into workflow_template_tasks(template_id,title,category,workload,sort_order) select wt.id,x.title,x.category,'Middel',x.ord from workflow_templates wt cross join (values('Micro/showroompagina deactiveren','Website',1),('Store locator verwijderen','Website',2),('Redirects instellen','Website',3),('Afspraakformulier verwijderen','Formulieren',4),('Deelnemer inactief zetten','DBMC',5),('Leadgeneratie stopzetten','Leadgeneratie',6),('Externe partijen informeren','Communicatie',7)) x(title,category,ord) where wt.name='Offboarding deelnemer';
-- Demo auth users are deliberately not hardcoded. Create/invite them in Authentication,
-- then use the documented helper script/admin screen to add profiles and realistic items.
