create extension if not exists pgcrypto;
create type public.item_status as enum ('Nieuw','Te bespreken','Ingepland','Actief','Afgerond','Gearchiveerd');
create type public.task_status as enum ('Backlog','Ingepland','Bezig','Wacht op input','Wacht op controle','Goedgekeurd','Gepubliceerd','Afgerond');
create type public.priority as enum ('Laag','Normaal','Hoog','Urgent');
create type public.workload as enum ('Klein','Middel','Groot');

create table public.roles(id uuid primary key default gen_random_uuid(),name text unique not null,description text,created_at timestamptz not null default now());
create table public.permissions(id uuid primary key default gen_random_uuid(),key text unique not null,description text);
create table public.role_permissions(role_id uuid references public.roles on delete cascade,permission_id uuid references public.permissions on delete cascade,primary key(role_id,permission_id));
create table public.profiles(id uuid primary key references auth.users on delete cascade,email text unique not null,full_name text not null,function_title text,role_id uuid references public.roles,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.user_permission_overrides(user_id uuid references public.profiles on delete cascade,permission_id uuid references public.permissions on delete cascade,allowed boolean not null,primary key(user_id,permission_id));
create or replace function public.has_permission(requested text) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles p join role_permissions rp on rp.role_id=p.role_id join permissions pe on pe.id=rp.permission_id where p.id=auth.uid() and p.is_active and pe.key=requested) and coalesce((select allowed from user_permission_overrides u join permissions pe on pe.id=u.permission_id where u.user_id=auth.uid() and pe.key=requested),true) or coalesce((select allowed from user_permission_overrides u join permissions pe on pe.id=u.permission_id where u.user_id=auth.uid() and pe.key=requested),false) $$;

create table public.channels(id uuid primary key default gen_random_uuid(),name text unique not null,active boolean not null default true,created_at timestamptz default now());
create table public.communication_profiles(id uuid primary key default gen_random_uuid(),name text unique not null,type text not null check(type in ('Concept','Private Label','Corporate','Land/organisatie','Overig')),country text,description text,logo_path text,audience text,tone_of_voice text,brand_style jsonb default '{}',communication_rules jsonb default '{}',active boolean not null default true,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table public.communication_profile_channels(profile_id uuid references public.communication_profiles on delete cascade,channel_id uuid references public.channels on delete cascade,primary key(profile_id,channel_id));
create table public.marketing_item_types(id uuid primary key default gen_random_uuid(),name text unique not null,active boolean default true);
create table public.marketing_items(id uuid primary key default gen_random_uuid(),title text not null,type_id uuid references public.marketing_item_types,summary text not null,description text,owner_id uuid not null references public.profiles,priority public.priority not null default 'Normaal',status public.item_status not null default 'Nieuw',start_date date,end_date date,publication_date date,supplier text,created_by uuid not null references public.profiles,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,deleted_at timestamptz,search_vector tsvector generated always as (to_tsvector('simple',coalesce(title,'')||' '||coalesce(summary,'')||' '||coalesce(description,''))) stored);
create table public.marketing_item_profiles(marketing_item_id uuid references public.marketing_items on delete cascade,profile_id uuid references public.communication_profiles,primary key(marketing_item_id,profile_id));
create table public.marketing_item_channels(marketing_item_id uuid references public.marketing_items on delete cascade,channel_id uuid references public.channels,primary key(marketing_item_id,channel_id));
create table public.tasks(id uuid primary key default gen_random_uuid(),marketing_item_id uuid references public.marketing_items,title text not null,description text,assignee_id uuid not null references public.profiles,channel_id uuid references public.channels,category text,status public.task_status not null default 'Backlog',priority public.priority not null default 'Normaal',workload public.workload not null default 'Middel',required boolean not null default true,deadline date,planned_date date,publication_date date,approval_required boolean not null default false,approver_id uuid references public.profiles,actual_hours numeric(7,2) check(actual_hours>=0),result_note text,result_url text,created_by uuid not null references public.profiles,created_at timestamptz default now(),updated_at timestamptz default now(),completed_at timestamptz,deleted_at timestamptz,check(not approval_required or approver_id is not null));
create table public.task_profiles(task_id uuid references public.tasks on delete cascade,profile_id uuid references public.communication_profiles,primary key(task_id,profile_id));
create table public.task_time_allocations(id uuid primary key default gen_random_uuid(),task_id uuid references public.tasks on delete cascade,profile_id uuid references public.communication_profiles,hours numeric(7,2) not null check(hours>0),created_at timestamptz default now(),unique(task_id,profile_id));
create table public.task_library(id uuid primary key default gen_random_uuid(),name text not null,description text,category text,workload public.workload,channel_id uuid references public.channels,active boolean default true,created_at timestamptz default now(),archived_at timestamptz);
create table public.workflow_templates(id uuid primary key default gen_random_uuid(),name text not null,type_id uuid references public.marketing_item_types,profile_id uuid references public.communication_profiles,country text,active boolean default true,created_at timestamptz default now(),archived_at timestamptz);
create table public.workflow_template_tasks(id uuid primary key default gen_random_uuid(),template_id uuid references public.workflow_templates on delete cascade,library_task_id uuid references public.task_library,title text not null,description text,category text,channel_id uuid references public.channels,workload public.workload default 'Middel',approval_required boolean default false,sort_order integer default 0);
create table public.comments(id uuid primary key default gen_random_uuid(),task_id uuid not null references public.tasks on delete cascade,author_id uuid not null references public.profiles,body text not null,created_at timestamptz default now(),deleted_at timestamptz);
create table public.attachments(id uuid primary key default gen_random_uuid(),marketing_item_id uuid references public.marketing_items,task_id uuid references public.tasks,uploaded_by uuid not null references public.profiles,file_name text not null,storage_path text unique not null,mime_type text not null,size_bytes bigint not null check(size_bytes between 1 and 20971520),created_at timestamptz default now(),deleted_at timestamptz,check(num_nonnulls(marketing_item_id,task_id)=1));
create table public.task_results(id uuid primary key default gen_random_uuid(),task_id uuid not null references public.tasks on delete cascade,type text not null check(type in ('url','text','file')),value text not null,attachment_id uuid references public.attachments,created_by uuid references public.profiles,created_at timestamptz default now());
create table public.approvals(id uuid primary key default gen_random_uuid(),task_id uuid references public.tasks on delete cascade,requested_by uuid references public.profiles,approver_id uuid references public.profiles,status text check(status in ('requested','approved','rejected')),comment text,created_at timestamptz default now(),decided_at timestamptz,check(status<>'rejected' or length(trim(comment))>0));
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles on delete cascade,type text not null,title text not null,body text,link text,read_at timestamptz,created_at timestamptz default now());
create table public.tags(id uuid primary key default gen_random_uuid(),name text unique not null,active boolean default true);
create table public.marketing_item_tags(marketing_item_id uuid references public.marketing_items on delete cascade,tag_id uuid references public.tags,primary key(marketing_item_id,tag_id));
create table public.recurrence_rules(id uuid primary key default gen_random_uuid(),title text not null,frequency text not null check(frequency in ('weekly','monthly','yearly','custom')),interval_count int not null default 1 check(interval_count>0),start_date date not null,end_date date,template_id uuid references public.workflow_templates,owner_id uuid references public.profiles,profile_id uuid references public.communication_profiles,next_run_date date,active boolean default true,created_at timestamptz default now());
create table public.recurrence_occurrences(rule_id uuid references public.recurrence_rules on delete cascade,occurrence_date date,marketing_item_id uuid references public.marketing_items,primary key(rule_id,occurrence_date));
create table public.activity_log(id uuid primary key default gen_random_uuid(),actor_id uuid references public.profiles,entity_type text not null,entity_id uuid not null,event text not null,old_values jsonb,new_values jsonb,created_at timestamptz not null default now());
create table public.settings(key text primary key,value jsonb not null,updated_at timestamptz default now());

create index tasks_assignee_status_idx on public.tasks(assignee_id,status); create index tasks_dates_idx on public.tasks(planned_date,deadline); create index tasks_item_idx on public.tasks(marketing_item_id); create index items_status_dates_idx on public.marketing_items(status,publication_date,start_date); create index item_search_idx on public.marketing_items using gin(search_vector); create index task_profiles_profile_idx on public.task_profiles(profile_id); create index activity_entity_idx on public.activity_log(entity_type,entity_id,created_at desc); create index notifications_user_idx on public.notifications(user_id,read_at,created_at desc);

alter table public.profiles enable row level security; alter table public.marketing_items enable row level security; alter table public.tasks enable row level security; alter table public.comments enable row level security; alter table public.attachments enable row level security; alter table public.notifications enable row level security; alter table public.activity_log enable row level security;
create policy profiles_read on public.profiles for select to authenticated using (is_active and public.has_permission('users.view'));
create policy items_read on public.marketing_items for select to authenticated using (public.has_permission('marketing_items.view'));
create policy items_create on public.marketing_items for insert to authenticated with check (public.has_permission('marketing_items.create') and created_by=auth.uid());
create policy items_update on public.marketing_items for update to authenticated using (public.has_permission('marketing_items.edit')) with check(public.has_permission('marketing_items.edit'));
create policy tasks_read on public.tasks for select to authenticated using(public.has_permission('tasks.view'));
create policy tasks_create on public.tasks for insert to authenticated with check(public.has_permission('tasks.create') and created_by=auth.uid());
create policy tasks_update on public.tasks for update to authenticated using(public.has_permission('tasks.edit') and (assignee_id=auth.uid() or public.has_permission('tasks.assign')));
create policy comments_read on public.comments for select to authenticated using(public.has_permission('tasks.view'));
create policy comments_create on public.comments for insert to authenticated with check(public.has_permission('comments.create') and author_id=auth.uid());
create policy attachments_read on public.attachments for select to authenticated using(public.has_permission('marketing_items.view'));
create policy attachments_create on public.attachments for insert to authenticated with check(public.has_permission('files.upload') and uploaded_by=auth.uid());
create policy notifications_own on public.notifications for select to authenticated using(user_id=auth.uid());
create policy notifications_mark_read on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy audit_read on public.activity_log for select to authenticated using(public.has_permission('marketing_items.view'));
-- No UPDATE/DELETE policy on activity_log: audit rows are immutable, including for admins.

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('marketing-files','marketing-files',false,20971520,array['application/pdf','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
create policy storage_read on storage.objects for select to authenticated using(bucket_id='marketing-files' and public.has_permission('marketing_items.view'));
create policy storage_upload on storage.objects for insert to authenticated with check(bucket_id='marketing-files' and public.has_permission('files.upload') and (storage.foldername(name))[1]=auth.uid()::text);
